### ISSUE TITLE
add ability to filter out NSFW memes

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#14]
give ability to filter out NSFW memes, perhaps by adding a flag. the default value will be to include them, but adjusting the value via flag can override that and exclude work-unfriendly content.

**Comment by akashsara** [comment]
I'll take this.

**Comment by cjwilburn** [comment]
go for it! thank you!

**Comment by jofftiquez** [comment]
No memes are bad memes. #notomemediscrimination #yesnsfwmemes HAHAHA i'm kidding.
