### ISSUE TITLE
Exit node/readLine after successful operation

### ISSUE THREAD

**Issue by GhostToast** [cjwilburn/dank-memes#24]
### Summary

Prompt does not seem to exit after running `index.js` or `roulette.js` successfully renders an image to browser. Currently requires pressing "CTR+C" to exit process.

### Expected Behavior

After image is successfully loaded, user should be free to do other things on terminal.

### Actual Behavior

Prompt appears to hang.

### Steps to Test

Run `node index.js` and return to terminal. The readLine maybe is still awaiting input?
Run `node roulette.js` and the same is experienced.

### Screenshot (if possible)
![image](https://user-images.githubusercontent.com/1346732/46552674-0856db80-c8a1-11e8-8c81-84b054d739f7.png)
It is awaiting further input and must be canceled.

### Describe Your Environment

- OS: Mac 10.13.6

**Comment by Jaace** [comment]
I can take a look into this.

**Comment by cjwilburn** [comment]
Go for it @Jaace
