### ISSUE TITLE
Code formatting standards, ESLint

### ISSUE THREAD

**Issue by Jaace** [cjwilburn/dank-memes#25]
### Summary
Currently, we have a few files with different indentation styles and a mix of tabs/spaces. Set up a basic eslint file to keep all contributors on the same page in terms of formatting and code style.

### Expected Behavior
ESlint, etc is set up with basic defaults to target indentation style, code formatting, etc.

**Comment by mfklauberg** [comment]
hey @Jaace, I submitted a PR for this issue #27
