### ISSUE TITLE
Add chalk and command-line-tool node modules

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#28]
### Summary

* Add `chalk` and `command-line-tools` modules in the `package.json`
* update `package-json.lock`
* update `yarn.lock`

### Expected Behavior

These changes should provide additional functionality for new features.

### Actual Behavior

n/a

### Steps to Test

Please confirm that your lock files are updated before submitting a pull request.

### Screenshot (if possible)
n/a

### Describe Your Environment

- OS: <-- Please provide a summary of the issue -->
- version: <-- Please provide a summary of the issue -->

**Comment by ClaraTersi** [comment]
Can I work on this?

**Comment by ocristian** [comment]
Sorry @ClaraTersi, I just send the PR.

**Comment by ClaraTersi** [comment]
No problem :)
