### ISSUE TITLE
Adjust contributors images

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#34]
### Summary

Adjust the size of the contributor images in `README.md` to make them smaller. 

Bonus points (and by bonus points, I mean my unending gratitude) if you can find a way to load contributors to the readme dynamically.

**Comment by trblackw** [comment]
I think I can help you out with this!

**Comment by cjwilburn** [comment]
Go for it!

**Comment by trblackw** [comment]
I'm actually a bit confused as to what you're asking for here. I'm assuming you'd be capable of making the images smaller yourself my reducing the height and width attributes. Is there something more specific you're going for? I'd feel silly if I opened a PR with just reduced heights and widths lol.

**Comment by cjwilburn** [comment]
Yes, I can do this myself, but I am attempting to give folks, especially those new to coding, git, or Github in particular, an opportunity to make a low-stakes contribution to this repo. Feel free to pass this up and let someone else take it on.

**Comment by trblackw** [comment]
Oh okay! Kind of you. I didn’t catch that. I’ll let someone else take it!

**Comment by cjwilburn** [comment]
Thanks! I've added the `good first issue` label so that some first-timers can take a pass at it.

**Comment by trblackw** [comment]
I’m not exactly a first timer but I still consider myself definitely a
beginner when it comes to making pull requests and contributing to open
source. Hacktoberfest has motivated me to step my PR game up!

**Comment by cjwilburn** [comment]
I'll be writing up some more issues this week, so stay tuned if you want to handle something a little tougher with this repo.

**Comment by klanti117** [comment]
would like to pick up this issue

**Comment by cjwilburn** [comment]
Please pick it up, @klanti117
