### ISSUE TITLE
write unit test for reddit meme generator in avajs

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#50]
### Summary

Write unit tests for `reddit.js` in [ava](https://github.com/avajs/ava)

**Comment by Jaace** [comment]
I can take a look

**Comment by Jaace** [comment]
Looks like maybe our reddit set up is way out of date unless I'm just doing something wrong, if so I'm gonna need to pivot as this isn't working in general, let alone tests haha:

`node reddit.js`

Results in many 403 tabs 🤔

**Comment by Jaace** [comment]
OK back on track - pushing up first iteration of fixes + tests.

**Comment by cjwilburn** [comment]
Thanks for digging in!

**Comment by cjwilburn** [comment]
Closed by #69. Nice! Thanks @Jaace
