### ISSUE TITLE
"me explaining to my mom meme generator

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#56]
### Summary

Using an image similar to this:

![tomymom](https://user-images.githubusercontent.com/529894/66094770-26fabb80-e563-11e9-8868-71aa53c5d83b.jpg)

Allow users to generate a meme that will write text over each person. Over the person with their hands out, allow the user to enter text saying what that person is explaining. Over the person with the fleece blanket, allow them to enter the name of the person responding followed by a colon (:) to portray a reaction image.

Write a unit test for this generator.

**Comment by justintucker** [comment]
Can I take this one?

**Comment by cjwilburn** [comment]
sure!

**Comment by cjwilburn** [comment]
this was closed by #73
