### ISSUE TITLE
refactor generators to work in generators directory

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#74]
### Summary

<-- Please provide a summary of the issue -->

### Expected Behavior

<-- Please provide a summary of the issue -->

### Actual Behavior

<-- Please provide a summary of the issue -->

### Steps to Test

<-- Please provide a summary of the issue -->

### Screenshot (if possible)

<-- Please provide a summary of the issue -->

### Describe Your Environment

- OS: <-- Please provide a summary of the issue -->
- version: <-- Please provide a summary of the issue -->

**Comment by justintucker** [comment]
👋 Hi CJ. For this issue, should the work follow the same pattern as the `yo-dawg-generator.js` setup?

**Comment by cjwilburn** [comment]
Hello @justintucker !! yes, please follow the same pattern as the yo-dawg-generator.

**Comment by cjwilburn** [comment]
resolved by #81
