### ISSUE TITLE
Improve Github Actions Integration

### ISSUE THREAD

**Issue by cjwilburn** [cjwilburn/dank-memes#84]
### Summary

1. Incorporate existing tests.
1. The build must pass.
1. make sure that it works with `yarn` and `npm`

**Comment by asadmansr** [comment]
Hi @cjwilburn, I can take a look into this if you like

**Comment by cjwilburn** [comment]
@asadmansr please go ahead.

**Comment by asadmansr** [comment]
Thanks! I've created the pull request to be reviewed here: https://github.com/cjwilburn/dank-memes/pull/87
